/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.Random;
import java.util.HashSet;
import java.util.TreeSet;
import java.util.ArrayList;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static Random randInt = new Random();

    public static int[] roll(int n)
    {
        int[] rolls = new int[n+1];
        for(int i = 0; i < n; i++)
        {
            int rollD6 = randInt.nextInt(7);
            rolls[i] = rollD6;
            System.out.println(rollD6);
        }
        return rolls;
    }

    public static boolean containsDuplicates(int[] arr)
    {
        boolean duplicates = false;
        for(int i1 : arr)
        {
            int count = 0;
            for(int i2: arr)
            {
                if(i1 == i2)
                {
                    count++;
                }
                if(count > 1)
                {
                    duplicates = true;
                    break;
                }
            }
        }
        return duplicates;

//        for(int i = 0; i < arr.size(); i++){
//            for(int j = 0; j < arr.size(); j++){
//                if (i != j && arr.get(i).equals(arr.get(j))){
//                    if(arr.get(i).equals(arr.get(j))){
//                        return true;
//                    }
//                }
//            }
//        }
    }

    public static int calculateAverage(int[] arr)
    {
        int total = 0;
        for(int i : arr)
        {
            total += i;
        }
        return total / arr.length;
    }

    public static int[] lowestAverage(int[][] matrix)
    {
        int[] lowAvgArr = new int[0];
        int lowest = 100000000;
        // double lowest = Double.POSITIVE_INFINITY
        for(int[] arr : matrix)
        {
            int arrAvg = calculateAverage(arr);
            if(arrAvg < lowest)
            {
                lowAvgArr = arr;
            }
        }
        return lowAvgArr;
    }

    static int[][] weeklyMonthTemperatures =
    {
        {66, 64, 58, 65, 71, 57, 60},
        {57, 65, 65, 70, 72, 65, 51},
        {55, 54, 60, 53, 59, 57, 61},
        {65, 56, 55, 52, 55, 62, 57}
    };

    public static String weatherMap(int[][] matrix)
    {
        HashSet<Integer> uniqueTemps = new HashSet<>();
        for(int[] arr : matrix)
        {
            for(int i : arr)
            {
                uniqueTemps.add(i);
            }
        }
        TreeSet<Integer> uniqueTempsTree = new TreeSet<>(uniqueTemps);
        int hightTemp = uniqueTempsTree.last();
        int lowTemp = uniqueTempsTree.first();
        String output = "High: "+ hightTemp +"\nLow: "+ lowTemp +"\n";
        for(int i = lowTemp; i < hightTemp; i++)
        {
            if(!uniqueTempsTree.contains(i))
            {
                output += "Never saw temperature: "+ i +"\n";
            }
        }
        return output;
    }

    public static void main(String[] args)
    {
        int[] testArr = {0,2,2,4};
        // boolean dupe = containsDuplicates(testArr);
        // roll(3);
        // System.out.println(calculateAverage(testArr));
        System.out.println(weatherMap(weeklyMonthTemperatures));
        System.out.println("hey");
    }

}
